sudo: required
services:
  - docker

before_install:
  - docker build -t nmc03/docker-react -f Dockerfile.dev .

script:
    #-e CI=true
  - docker run -e CI=true nmc03/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-236010346834"
  bucket_path: "frontend"
  on:
    branch: main
  # Encrypted access keys for IAM User in "Evironment Variables" inside of Travis-CI
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
